---
name: rebuild-static
on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '23'
      - name: Build code
        run: |-
          cd app
          npm install
          npm run build
          cp dist/index.html dist/404.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: app/dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4